services:
- type: web
  name: nerv-demo
  env: python
  plan: free
  buildCommand: "pip install -r requirements.txt"
  startCommand: "gunicorn app:server"
  envVars:
    - key: PYTHON_VERSION
      value: 3.10.0